### ISSUE TITLE
Panic when returning an ast() with accidental token as name

### ISSUE THREAD

**Issue by scolsen** [tokay-lang/tokay#56]
Small reproducible example:

```
ast_print(HelloWorld)
  
HelloWorld : @{
  'Hello' _ 'World' ast('hello')
}

tokay hello.tok -- "Hello World"
```

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'
```

**Comment by phorward** [comment]
Hello @scolsen,
thank you for filing this issue!

The problem of this issue is both a bug, which was fixed by 48b60c1, but there is also a use error:
`ast('hello')`is a function call where the first parameter is a match token that matches the string `hello` in the input. The wanted behavior, which also fixes above program is to turn the parameter into a string, with double quotation marks: `ast("hello")`.

This is the corrected version of your program:
```tokay
ast_print(HelloWorld)
  
HelloWorld : @{
  'Hello' _ 'World' ast("hello")
}
```
